### ISSUE TITLE
Can I tell the dumper not to emit the !!str when it's a quoted string scalar?

### ISSUE THREAD

**Issue by aliak00** [dlang-community/D-YAML#253]
I read it a yaml file that looks like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-testing-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hello-testing-cluster-static-ip"
    networking.gke.io/managed-certificates: "api-certificate"
```

And all I want to do is change the value of `networking.gke.io/managed-certificates` from to `"api-certificate,api2-certificate"` But the best I can do is this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-testing-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: !!str "hello-testing-cluster-static-ip"
    networking.gke.io/managed-certificates: !!str "api-certificate,api2-certificate"
```

I.e. I can't get rid of the `!!str` tag. 

How can I do that?
