### ISSUE TITLE
Default scalar style never chooses literal and folded styles

### ISSUE THREAD

**Issue by Herringway** [dlang-community/D-YAML#341]
For long strings, especially those with newlines, these styles are the best for readability. Currently, dyaml chooses quoted styles, resulting in output littered with `\<actual newline>` AND `\n`, which are annoying to read.
An example submitted to me:
```YAML
%YAML 1.1
---
name: tar
doc: "libtar - small library for manipulating TAR files.\n\nAuthor:\n\nMark D. Roth,\
  \ roth@uiuc.edu\n  Campus Information Technologies and Educational Services\n  University\
  \ of Illinois at Urbana-Champaign\n\n\nadded by my app!\n    yeeey!\n"
types: null
objects: null
functions: null
ignored-functions: null
```
A much more readable default for the doc value would be literal style, resulting in:
```YAML
%YAML 1.1
---
name: tar
doc: |
  libtar - small library for manipulating TAR files.
  
  Author:
  
  Mark D. Roth, roth@uiuc.edu
    Campus Information Technologies and Educational Services
    University of Illinois at Urbana-Champaign
  
  
  added by my app!
      yeeey!
types: null
objects: null
functions: null
ignored-functions: null
```
