### ISSUE TITLE
Provide up-to-date and easily browseable docs

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/D-YAML#57]
Imho instead of committing the docs in the source code, we could run ddox on Travis/Circle Ci
For CircleCi it can be reduced down to something like:

```yml
test:
  override:
    - make -f doc/Makefile html # or any other command to create the docs
deployment:
  aws:
    branch: master
    commands:
      - AWS_DEFAULT_REGION=eu-west-1 aws s3 sync --acl public-read --delete web s3://docs.mir.dlang.io/latest
```

[source](https://github.com/libmir/mir/blob/master/circle.yml)

The AWS S3 key can be conveniently added to CircleCi via their web interface.
